Repository mozilla-mobile/mozilla-vpn-client, pull requests merged in 2022-10, with the labels that each got.

#4577 Sign the VPN addons using the release key
  taskcluster/mozillavpn_taskgraph/transforms/signing.py
Labels: CI

#4598 Fix release-promotion trying to push to dep bucket in prod
  taskcluster/ci/beetmover/kind.yml
Labels: bug

#4599 Ignore deprecated addons when populating release-artifacts
  taskcluster/mozillavpn_taskgraph/transforms/beetmover.py
Labels: bug

#4714 Upload macos release candidates to mac directory
  taskcluster/mozillavpn_taskgraph/transforms/beetmover.py
Labels: bug

#4745 Taskcluster: Check compat with "next" QT
  src/commands/commandui.cpp
  src/connectionbenchmark/benchmarktasktransfer.cpp
  taskcluster/ci/build/android.yml
  taskcluster/ci/docker-image/kind.yml
Labels: android, CI
